# Generated by Django 3.0.3 on 2020-02-26 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('national_id', models.IntegerField()),
                ('cell_no', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('business_area', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
