# Generated by Django 3.0.3 on 2020-02-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200228_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='surname_name',
            new_name='surname',
        ),
    ]
