# Generated by Django 3.0.3 on 2020-03-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200228_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname']},
        ),
    ]
