# Generated by Django 3.0.3 on 2020-02-26 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('repay_amount', models.IntegerField()),
                ('cycles', models.IntegerField()),
                ('current_amount', models.IntegerField()),
                ('mode_cycles', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cycles', models.IntegerField()),
                ('mode', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transact.loan')),
            ],
        ),
    ]
