# Generated by Django 3.0.3 on 2020-03-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200307_0843'),
        ('transact', '0002_auto_20200307_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='mode',
            new_name='mode_of_payment',
        ),
        migrations.AlterField(
            model_name='loan',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transact.Loan'),
        ),
    ]
